### ISSUE TITLE
issue: not refreshing immediately after applying the layout.

### ISSUE THREAD

**Issue by ltdrdata** [phineas-pta/comfyui-auto-nodes-layout#1]
```
app.graph.setDirtyCanvas(true, true);
```

Above code Should be added to these points.

https://github.com/phineas-pta/comfyui-auto-nodes-layout/blob/1f8ed9c359c3eb14f4be77022360ee233092f768/web/autoLayout.js#L125

https://github.com/phineas-pta/comfyui-auto-nodes-layout/blob/1f8ed9c359c3eb14f4be77022360ee233092f768/web/autoLayout.js#L84

**Comment by phineas-pta** [comment]
tysm again & again 😆 looking for that shit
